### ISSUE TITLE
作者很细心，我也做了类似的东西。望交流

### ISSUE THREAD

**Issue by kaleai** [iwgang/FamiliarRecyclerView#1]
https://github.com/tianzhijiexian/ExRecyclerView qq:460412008

**Comment by iwgang** [comment]
^ ^ 原来大神也有类似的库，貌似有一点重复轮子了

做这个库的原因主要是最近想把公司项目原来的ListView和GridView迁移到RecyclerView，但有很多东西按原生RecyclerView去改进的话工作量非常大，然后就去找了些相关的库，但都不是特别符合，就参考ListView源码动手写了个
