### ISSUE TITLE
FamiliarRecyclerViewOnScrollListener bug

### ISSUE THREAD

**Issue by qq524007127** [iwgang/FamiliarRecyclerView#10]
自定义LayoutManager添加OnCrollLisnter报空指针异常

**Comment by iwgang** [comment]
FamiliarRecyclerViewOnScrollListener.java是一个独立类，代码量不大，建议自定义LayoutManager的时候，如果出现问题或者不能满足需求的情况下，复制FamiliarRecyclerViewOnScrollListener.java的源码进行定制修改
