### ISSUE TITLE
请问如何自定义下拉刷新动画？

### ISSUE THREAD

**Issue by Lsy1992** [iwgang/FamiliarRecyclerView#12]
现在看到的下拉刷新是Google官方的刷新控件，而且颜色是黑色的不能更改，请求提供一个方法可以自行设置刷新动画

**Comment by iwgang** [comment]
FamiliarRefreshRecyclerView就是继承的SwipeRefreshLayout，所以肯定是能设置刷新控件颜色的

目前只是实现了官方SwipeRefreshLayout的刷新文字，不能自定义下拉刷新动画，这块可以自己去继承或封装实现，该库可以理解为就是个改良成像Listview的Recyclerview
