### ISSUE TITLE
正确设置加载更多代码但是滑到底部不执行onloadmore方法可能是什么原因？

### ISSUE THREAD

**Issue by 379548560** [iwgang/FamiliarRecyclerView#17]
rv_home.setPullRefreshEnabled(true);
        rv_home.setLoadMoreEnabled(true);
        rv_home.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                time = 0;
                refreshData();
            }
        });
        loadMoreView = new LoadMoreView(context);
        rv_home.setLoadMoreView(loadMoreView);
        rv_home.setOnLoadMoreListener(new FamiliarRefreshRecyclerView.OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                Log.i(TAG, "onLoadMore执行了");
                refreshData();
            }
        });

**Comment by iwgang** [comment]
先跑下Demo

**Comment by 379548560** [comment]
demo我跑了 是可以的  但是我的配置和demo是一样的  就是不能加载更多~~
方便微信或者qq么

**Comment by 379548560** [comment]
这个库我之前在另一个项目也用过是ok的 但是现在不知道哪出问题了

**Comment by iwgang** [comment]
这样很难定位，方便的话提供下相关Demo

**Comment by 379548560** [comment]
`<cn.iwgang.familiarrecyclerview.FamiliarRefreshRecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/title_bar_home"
        android:background="@color/bg"
        android:scrollbars="vertical"
        android:tag="rv_home"
        app:frv_divider="@null"
        app:frv_dividerHeight="0.5dp"
        app:frv_emptyView="@id/tv_home_empty"
        app:frv_isEmptyViewKeepShowHeadOrFooter="false"
        app:frv_layoutManager="linear"
        app:frv_layoutManagerOrientation="vertical" />`

`//刷新数据
        rv_home.setPullRefreshEnabled(true);
        loadMoreView = new LoadMoreView(context);
        rv_home.setLoadMoreView(loadMoreView);
        rv_home.setLoadMoreEnabled(true);
        rv_home.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                time = 0;
                refreshData();
            }
        });
        rv_home.setOnLoadMoreListener(new FamiliarRefreshRecyclerView.OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                Log.i(TAG, "onLoadMore执行了");
                refreshData();
            }
        });
        if (null == adapter) {
            adapter = new HomeAdapter();
            rv_home.setAdapter(adapter);
        } else {
            rv_home.setAdapter(adapter);
        }`

**Comment by 379548560** [comment]
相关代码就这些

**Comment by iwgang** [comment]
@379548560 现在可以了么？

**Comment by iwgang** [comment]
我用你代码测试是正常的，确认一下是不是布局问题，没有测量到RV的准备高度，导致滚动到底部时不知道应该触发事件
