### ISSUE TITLE
在代码中setEmptyView()，isKeepShowHeadOrFooter==false，空界面显示不了

### ISSUE THREAD

**Issue by 1280103995** [iwgang/FamiliarRecyclerView#24]

**Comment by iwgang** [comment]
![image](https://user-images.githubusercontent.com/3657121/34472665-ae0fb4cc-efa1-11e7-8589-b08507dcd3c8.png)

调用的这个方法？

**Comment by 1280103995** [comment]
对的

**Comment by 1280103995** [comment]
之前没说清楚，具体情况是：
View empty = LayoutInflater.from(this).inflate(R.layout.empty_view, recyclerView, false);
recyclerView.setEmptyView(empty);
这种方式就不会显示empty。

但是如果emptyView是放在跟recyclerView同一个xml，像demo中的那样，然后
mRecyclerView.setEmptyView(findViewById(R.id.tv_empty));
这样就能显示emptyView

**Comment by iwgang** [comment]
这个确实是如此的设计，和以前的 ListView 处理一样
