### ISSUE TITLE
onScrolledToBottom()这个方法不知道为啥我的会走两遍或者三遍

### ISSUE THREAD

**Issue by Kenmmm** [iwgang/FamiliarRecyclerView#7]
onScrolledToBottom()这个方法不知道为啥我的会走两遍或者三遍，后面的数据有重复，搞了半天，以为自己写的问题，debug看了一下，有的时候下滑很快的时候这个方法会走两遍

**Comment by iwgang** [comment]
如果没有重写isIdleCallBack()并return false的话，默认要在 底部并且手指松开 才会回调，我刚又测试了几次，均无发现此问题

请测试一下demo代码是否有此问题，并提供一下测试机型，谢谢了

**Comment by Kenmmm** [comment]
和你的demo基本差不多，也没重写你说的这个方法，我在bottom里面加了一个boolean判断的，可以，但是没发现你的这个是什么原因

**Comment by iwgang** [comment]
具体我这边也不清楚原因，因为没能重现出来
FamiliarRecyclerViewOnScrollListener.java是一个完全独立的类，你可以直接复制出去改里面的代码调试一下

如果定位问题原因并能解决的话，希望能提交PR，谢谢了
