### ISSUE TITLE
分割线的问题

### ISSUE THREAD

**Issue by pengbs** [iwgang/FamiliarRecyclerView#9]
您好，这个库非常好用，但是我在使用竖向grid布局的时候，添加了分割线，但是发现第一行的上边和第一列的左边都没有分割线，您知道什么原因吗？万分感谢

**Comment by iwgang** [comment]
方便提供下完整配置么？

另外你跑下demo，如果demo也有类似情况，那就是机型问题了，到时再麻烦提供一下机型，我再找找原因

**Comment by pengbs** [comment]
不是机型问题，就是最上边和最左边的分割线没有

**Comment by pengbs** [comment]
麻烦你有时间可以确认下，我实在找不出问题在哪里，非常谢谢

**Comment by iwgang** [comment]
你试下Demo里面的有没有

**Comment by pengbs** [comment]
一样的啊，我发现是绘制分割线的时候只绘制了每个item的底部和右边，导致最上边和最左边的没有绘制

**Comment by iwgang** [comment]
分割线是只绘底加右的（最后一列的右不绘制），按正常需求去理解也是只会有两个边有线，因是用于两个itemView之间的一个分割而已

item的左右不能设置分割线，如果设置边距可以用frv_itemViewBothSidesMargin，如果想左右也有颜色给itemView加个底色就好了

然后recyclerview的顶部和底部在有headerView或footerView的场景下，使用frv_headerDividersEnabled或frv_footerDividersEnabled（和Listview一样实现）

**Comment by pengbs** [comment]
嗯，明白了
